### ISSUE TITLE
Win10_LockPicker no Hash possible when the Username has a space

### ISSUE THREAD

**Issue by pixelwasser** [mame82/P4wnP1#121] opened 2017-09-26 18:15 UTC
Hello,

I have found maybe the next issue. Currently it seems that the Win10_LockPicker payload is only able to collect hashes from single user Name like "DemoUser" if there is a space in the Username like "Demo User" the script tries to collect the hash from "Demo" which doesn't exist on the machine.

Sincerley
Jan

**Comment by pixelwasser** [comment] 2017-09-28 06:30
Target was a Windows 10 1607

**Comment by Swiftb0y** [comment] 2017-09-28 13:48
Even though you explained your issue very clearly, I fear mame is the only one that can help you. So be patient for a view days and you'll probably get a good answer.

**Comment by mame82** [comment] 2017-10-11 16:41
The root cause which allowed this payliad to work was fixed with KB4041691. So I'll give no further support on this, but a writeup is on the way

**Closed by mame82** 2017-10-11 16:41 UTC
